---
meta:
  resource_pools:
    small:
      cloud_properties:
        instance_type: Standard_F1
    medium:
      cloud_properties:
          instance_type: Standard_F2
    large:
      cloud_properties:
          instance_type: Standard_F4
    cell:
      cloud_properties:
          instance_type: Standard_D12_v2

iaas_settings:
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: (( meta.resource_pools.large.cloud_properties ))
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: brain_z1
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cc_bridge_z1
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cell_z1
      cloud_properties: (( meta.resource_pools.cell.cloud_properties ))
    - name: colocated_z1
      cloud_properties: (( meta.resource_pools.medium.cloud_properties ))
    - name: database_z1
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: route_emitter_z1
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: errand
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))

# z2 & z3 are used for high-available deployments
# You can safely remove them if you run a single-zone deployment
    - name: access_z2
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: brain_z2
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cc_bridge_z2
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cell_z2
      cloud_properties: (( meta.resource_pools.cell.cloud_properties ))
    - name: colocated_z2
      cloud_properties: (( meta.resource_pools.medium.cloud_properties ))
    - name: database_z2
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: route_emitter_z2
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: access_z3
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: brain_z3
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cc_bridge_z3
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: cell_z3
      cloud_properties: (( meta.resource_pools.cell.cloud_properties ))
    - name: colocated_z3
      cloud_properties: (( meta.resource_pools.medium.cloud_properties ))
    - name: database_z3
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))
    - name: route_emitter_z3
      cloud_properties: (( meta.resource_pools.small.cloud_properties ))

  subnet_configs:
    - name: diego1
      type: manual
      subnets:
      - cloud_properties:
          security_group: REPLACE_WITH_NSG_NAME_FOR_CLOUD_FOUNDRY
          subnet_name: REPLACE_WITH_SUBNET_NAME_FOR_CLOUD_FOUNDRY
          virtual_network_name: REPLACE_WITH_VNET_NAME
        dns:
        - REPLACE_WITH_DNS
        gateway: 10.0.16.1
        range: 10.0.16.0/20
        reserved:
        # reserved by cf (assume cf use range 10.0.16.0/24)
        - 10.0.16.2 - 10.0.16.255
        static: []
# diego2 & diego3 subnets are used for high-available deployments
# Currently Azure only support single zone, so z2 and z3 are not used.
    - name: diego2
      type: manual
      subnets: (( iaas_settings.subnet_configs.diego1.subnets ))
    - name: diego3
      type: manual
      subnets: (( iaas_settings.subnet_configs.diego1.subnets ))

